name: searchapplication
description: "New Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_riverpod: ^2.1.1 # 追加
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.1.3+1
  flutter_overboard: ^3.1.3

flutter_native_splash:
  color: '#add8e6'
  image: 'assets/images/logo.png'
  color_dark: '#262626'
  image_dark: 'assets/images/logo.png'
  fullscreen: true
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  android_12:
    icon_background_color: '#add8e6'
    image: 'assets/images/logo.png'
    icon_background_color_dark: '#262626'
    image_dark: 'assets/images/logo.png'

dev_dependencies:
  flutter_native_splash: ^2.1.3+1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/  # 画像ファイルを指定

  uses-material-design: true
